// Code generated by ent, DO NOT EDIT.

package booking

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/fulltimegodev/hotel-reservation/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldUserID, v))
}

// RoomID applies equality check predicate on the "room_id" field. It's identical to RoomIDEQ.
func RoomID(v int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldRoomID, v))
}

// NumPersons applies equality check predicate on the "num_persons" field. It's identical to NumPersonsEQ.
func NumPersons(v int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldNumPersons, v))
}

// FromDate applies equality check predicate on the "from_date" field. It's identical to FromDateEQ.
func FromDate(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldFromDate, v))
}

// TillDate applies equality check predicate on the "till_date" field. It's identical to TillDateEQ.
func TillDate(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldTillDate, v))
}

// Canceled applies equality check predicate on the "canceled" field. It's identical to CanceledEQ.
func Canceled(v bool) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldCanceled, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldUserID, vs...))
}

// RoomIDEQ applies the EQ predicate on the "room_id" field.
func RoomIDEQ(v int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldRoomID, v))
}

// RoomIDNEQ applies the NEQ predicate on the "room_id" field.
func RoomIDNEQ(v int) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldRoomID, v))
}

// RoomIDIn applies the In predicate on the "room_id" field.
func RoomIDIn(vs ...int) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldRoomID, vs...))
}

// RoomIDNotIn applies the NotIn predicate on the "room_id" field.
func RoomIDNotIn(vs ...int) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldRoomID, vs...))
}

// NumPersonsEQ applies the EQ predicate on the "num_persons" field.
func NumPersonsEQ(v int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldNumPersons, v))
}

// NumPersonsNEQ applies the NEQ predicate on the "num_persons" field.
func NumPersonsNEQ(v int) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldNumPersons, v))
}

// NumPersonsIn applies the In predicate on the "num_persons" field.
func NumPersonsIn(vs ...int) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldNumPersons, vs...))
}

// NumPersonsNotIn applies the NotIn predicate on the "num_persons" field.
func NumPersonsNotIn(vs ...int) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldNumPersons, vs...))
}

// NumPersonsGT applies the GT predicate on the "num_persons" field.
func NumPersonsGT(v int) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldNumPersons, v))
}

// NumPersonsGTE applies the GTE predicate on the "num_persons" field.
func NumPersonsGTE(v int) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldNumPersons, v))
}

// NumPersonsLT applies the LT predicate on the "num_persons" field.
func NumPersonsLT(v int) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldNumPersons, v))
}

// NumPersonsLTE applies the LTE predicate on the "num_persons" field.
func NumPersonsLTE(v int) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldNumPersons, v))
}

// FromDateEQ applies the EQ predicate on the "from_date" field.
func FromDateEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldFromDate, v))
}

// FromDateNEQ applies the NEQ predicate on the "from_date" field.
func FromDateNEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldFromDate, v))
}

// FromDateIn applies the In predicate on the "from_date" field.
func FromDateIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldFromDate, vs...))
}

// FromDateNotIn applies the NotIn predicate on the "from_date" field.
func FromDateNotIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldFromDate, vs...))
}

// FromDateGT applies the GT predicate on the "from_date" field.
func FromDateGT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldFromDate, v))
}

// FromDateGTE applies the GTE predicate on the "from_date" field.
func FromDateGTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldFromDate, v))
}

// FromDateLT applies the LT predicate on the "from_date" field.
func FromDateLT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldFromDate, v))
}

// FromDateLTE applies the LTE predicate on the "from_date" field.
func FromDateLTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldFromDate, v))
}

// TillDateEQ applies the EQ predicate on the "till_date" field.
func TillDateEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldTillDate, v))
}

// TillDateNEQ applies the NEQ predicate on the "till_date" field.
func TillDateNEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldTillDate, v))
}

// TillDateIn applies the In predicate on the "till_date" field.
func TillDateIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldTillDate, vs...))
}

// TillDateNotIn applies the NotIn predicate on the "till_date" field.
func TillDateNotIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldTillDate, vs...))
}

// TillDateGT applies the GT predicate on the "till_date" field.
func TillDateGT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldTillDate, v))
}

// TillDateGTE applies the GTE predicate on the "till_date" field.
func TillDateGTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldTillDate, v))
}

// TillDateLT applies the LT predicate on the "till_date" field.
func TillDateLT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldTillDate, v))
}

// TillDateLTE applies the LTE predicate on the "till_date" field.
func TillDateLTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldTillDate, v))
}

// CanceledEQ applies the EQ predicate on the "canceled" field.
func CanceledEQ(v bool) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldCanceled, v))
}

// CanceledNEQ applies the NEQ predicate on the "canceled" field.
func CanceledNEQ(v bool) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldCanceled, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Booking {
	return predicate.Booking(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Booking {
	return predicate.Booking(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoom applies the HasEdge predicate on the "room" edge.
func HasRoom() predicate.Booking {
	return predicate.Booking(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomTable, RoomColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoomWith applies the HasEdge predicate on the "room" edge with a given conditions (other predicates).
func HasRoomWith(preds ...predicate.Room) predicate.Booking {
	return predicate.Booking(func(s *sql.Selector) {
		step := newRoomStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Booking) predicate.Booking {
	return predicate.Booking(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Booking) predicate.Booking {
	return predicate.Booking(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Booking) predicate.Booking {
	return predicate.Booking(sql.NotPredicates(p))
}
