// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fulltimegodev/hotel-reservation/ent/booking"
	"github.com/fulltimegodev/hotel-reservation/ent/room"
	"github.com/fulltimegodev/hotel-reservation/ent/user"
)

// BookingCreate is the builder for creating a Booking entity.
type BookingCreate struct {
	config
	mutation *BookingMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *BookingCreate) SetUserID(v int) *BookingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRoomID sets the "room_id" field.
func (_c *BookingCreate) SetRoomID(v int) *BookingCreate {
	_c.mutation.SetRoomID(v)
	return _c
}

// SetNumPersons sets the "num_persons" field.
func (_c *BookingCreate) SetNumPersons(v int) *BookingCreate {
	_c.mutation.SetNumPersons(v)
	return _c
}

// SetFromDate sets the "from_date" field.
func (_c *BookingCreate) SetFromDate(v time.Time) *BookingCreate {
	_c.mutation.SetFromDate(v)
	return _c
}

// SetTillDate sets the "till_date" field.
func (_c *BookingCreate) SetTillDate(v time.Time) *BookingCreate {
	_c.mutation.SetTillDate(v)
	return _c
}

// SetCanceled sets the "canceled" field.
func (_c *BookingCreate) SetCanceled(v bool) *BookingCreate {
	_c.mutation.SetCanceled(v)
	return _c
}

// SetNillableCanceled sets the "canceled" field if the given value is not nil.
func (_c *BookingCreate) SetNillableCanceled(v *bool) *BookingCreate {
	if v != nil {
		_c.SetCanceled(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *BookingCreate) SetUser(v *User) *BookingCreate {
	return _c.SetUserID(v.ID)
}

// SetRoom sets the "room" edge to the Room entity.
func (_c *BookingCreate) SetRoom(v *Room) *BookingCreate {
	return _c.SetRoomID(v.ID)
}

// Mutation returns the BookingMutation object of the builder.
func (_c *BookingCreate) Mutation() *BookingMutation {
	return _c.mutation
}

// Save creates the Booking in the database.
func (_c *BookingCreate) Save(ctx context.Context) (*Booking, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BookingCreate) SaveX(ctx context.Context) *Booking {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BookingCreate) defaults() {
	if _, ok := _c.mutation.Canceled(); !ok {
		v := booking.DefaultCanceled
		_c.mutation.SetCanceled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BookingCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Booking.user_id"`)}
	}
	if _, ok := _c.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "Booking.room_id"`)}
	}
	if _, ok := _c.mutation.NumPersons(); !ok {
		return &ValidationError{Name: "num_persons", err: errors.New(`ent: missing required field "Booking.num_persons"`)}
	}
	if _, ok := _c.mutation.FromDate(); !ok {
		return &ValidationError{Name: "from_date", err: errors.New(`ent: missing required field "Booking.from_date"`)}
	}
	if _, ok := _c.mutation.TillDate(); !ok {
		return &ValidationError{Name: "till_date", err: errors.New(`ent: missing required field "Booking.till_date"`)}
	}
	if _, ok := _c.mutation.Canceled(); !ok {
		return &ValidationError{Name: "canceled", err: errors.New(`ent: missing required field "Booking.canceled"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Booking.user"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "Booking.room"`)}
	}
	return nil
}

func (_c *BookingCreate) sqlSave(ctx context.Context) (*Booking, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BookingCreate) createSpec() (*Booking, *sqlgraph.CreateSpec) {
	var (
		_node = &Booking{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(booking.Table, sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.NumPersons(); ok {
		_spec.SetField(booking.FieldNumPersons, field.TypeInt, value)
		_node.NumPersons = value
	}
	if value, ok := _c.mutation.FromDate(); ok {
		_spec.SetField(booking.FieldFromDate, field.TypeTime, value)
		_node.FromDate = value
	}
	if value, ok := _c.mutation.TillDate(); ok {
		_spec.SetField(booking.FieldTillDate, field.TypeTime, value)
		_node.TillDate = value
	}
	if value, ok := _c.mutation.Canceled(); ok {
		_spec.SetField(booking.FieldCanceled, field.TypeBool, value)
		_node.Canceled = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.UserTable,
			Columns: []string{booking.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.RoomTable,
			Columns: []string{booking.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoomID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BookingCreateBulk is the builder for creating many Booking entities in bulk.
type BookingCreateBulk struct {
	config
	err      error
	builders []*BookingCreate
}

// Save creates the Booking entities in the database.
func (_c *BookingCreateBulk) Save(ctx context.Context) ([]*Booking, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Booking, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BookingCreateBulk) SaveX(ctx context.Context) []*Booking {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
