// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fulltimegodev/hotel-reservation/ent/booking"
	"github.com/fulltimegodev/hotel-reservation/ent/predicate"
	"github.com/fulltimegodev/hotel-reservation/ent/room"
	"github.com/fulltimegodev/hotel-reservation/ent/user"
)

// BookingUpdate is the builder for updating Booking entities.
type BookingUpdate struct {
	config
	hooks    []Hook
	mutation *BookingMutation
}

// Where appends a list predicates to the BookingUpdate builder.
func (_u *BookingUpdate) Where(ps ...predicate.Booking) *BookingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BookingUpdate) SetUserID(v int) *BookingUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BookingUpdate) SetNillableUserID(v *int) *BookingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoomID sets the "room_id" field.
func (_u *BookingUpdate) SetRoomID(v int) *BookingUpdate {
	_u.mutation.SetRoomID(v)
	return _u
}

// SetNillableRoomID sets the "room_id" field if the given value is not nil.
func (_u *BookingUpdate) SetNillableRoomID(v *int) *BookingUpdate {
	if v != nil {
		_u.SetRoomID(*v)
	}
	return _u
}

// SetNumPersons sets the "num_persons" field.
func (_u *BookingUpdate) SetNumPersons(v int) *BookingUpdate {
	_u.mutation.ResetNumPersons()
	_u.mutation.SetNumPersons(v)
	return _u
}

// SetNillableNumPersons sets the "num_persons" field if the given value is not nil.
func (_u *BookingUpdate) SetNillableNumPersons(v *int) *BookingUpdate {
	if v != nil {
		_u.SetNumPersons(*v)
	}
	return _u
}

// AddNumPersons adds value to the "num_persons" field.
func (_u *BookingUpdate) AddNumPersons(v int) *BookingUpdate {
	_u.mutation.AddNumPersons(v)
	return _u
}

// SetFromDate sets the "from_date" field.
func (_u *BookingUpdate) SetFromDate(v time.Time) *BookingUpdate {
	_u.mutation.SetFromDate(v)
	return _u
}

// SetNillableFromDate sets the "from_date" field if the given value is not nil.
func (_u *BookingUpdate) SetNillableFromDate(v *time.Time) *BookingUpdate {
	if v != nil {
		_u.SetFromDate(*v)
	}
	return _u
}

// SetTillDate sets the "till_date" field.
func (_u *BookingUpdate) SetTillDate(v time.Time) *BookingUpdate {
	_u.mutation.SetTillDate(v)
	return _u
}

// SetNillableTillDate sets the "till_date" field if the given value is not nil.
func (_u *BookingUpdate) SetNillableTillDate(v *time.Time) *BookingUpdate {
	if v != nil {
		_u.SetTillDate(*v)
	}
	return _u
}

// SetCanceled sets the "canceled" field.
func (_u *BookingUpdate) SetCanceled(v bool) *BookingUpdate {
	_u.mutation.SetCanceled(v)
	return _u
}

// SetNillableCanceled sets the "canceled" field if the given value is not nil.
func (_u *BookingUpdate) SetNillableCanceled(v *bool) *BookingUpdate {
	if v != nil {
		_u.SetCanceled(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BookingUpdate) SetUser(v *User) *BookingUpdate {
	return _u.SetUserID(v.ID)
}

// SetRoom sets the "room" edge to the Room entity.
func (_u *BookingUpdate) SetRoom(v *Room) *BookingUpdate {
	return _u.SetRoomID(v.ID)
}

// Mutation returns the BookingMutation object of the builder.
func (_u *BookingUpdate) Mutation() *BookingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BookingUpdate) ClearUser() *BookingUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearRoom clears the "room" edge to the Room entity.
func (_u *BookingUpdate) ClearRoom() *BookingUpdate {
	_u.mutation.ClearRoom()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookingUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Booking.user"`)
	}
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Booking.room"`)
	}
	return nil
}

func (_u *BookingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(booking.Table, booking.Columns, sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NumPersons(); ok {
		_spec.SetField(booking.FieldNumPersons, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumPersons(); ok {
		_spec.AddField(booking.FieldNumPersons, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FromDate(); ok {
		_spec.SetField(booking.FieldFromDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TillDate(); ok {
		_spec.SetField(booking.FieldTillDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Canceled(); ok {
		_spec.SetField(booking.FieldCanceled, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.UserTable,
			Columns: []string{booking.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.UserTable,
			Columns: []string{booking.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.RoomTable,
			Columns: []string{booking.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.RoomTable,
			Columns: []string{booking.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{booking.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookingUpdateOne is the builder for updating a single Booking entity.
type BookingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookingMutation
}

// SetUserID sets the "user_id" field.
func (_u *BookingUpdateOne) SetUserID(v int) *BookingUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BookingUpdateOne) SetNillableUserID(v *int) *BookingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoomID sets the "room_id" field.
func (_u *BookingUpdateOne) SetRoomID(v int) *BookingUpdateOne {
	_u.mutation.SetRoomID(v)
	return _u
}

// SetNillableRoomID sets the "room_id" field if the given value is not nil.
func (_u *BookingUpdateOne) SetNillableRoomID(v *int) *BookingUpdateOne {
	if v != nil {
		_u.SetRoomID(*v)
	}
	return _u
}

// SetNumPersons sets the "num_persons" field.
func (_u *BookingUpdateOne) SetNumPersons(v int) *BookingUpdateOne {
	_u.mutation.ResetNumPersons()
	_u.mutation.SetNumPersons(v)
	return _u
}

// SetNillableNumPersons sets the "num_persons" field if the given value is not nil.
func (_u *BookingUpdateOne) SetNillableNumPersons(v *int) *BookingUpdateOne {
	if v != nil {
		_u.SetNumPersons(*v)
	}
	return _u
}

// AddNumPersons adds value to the "num_persons" field.
func (_u *BookingUpdateOne) AddNumPersons(v int) *BookingUpdateOne {
	_u.mutation.AddNumPersons(v)
	return _u
}

// SetFromDate sets the "from_date" field.
func (_u *BookingUpdateOne) SetFromDate(v time.Time) *BookingUpdateOne {
	_u.mutation.SetFromDate(v)
	return _u
}

// SetNillableFromDate sets the "from_date" field if the given value is not nil.
func (_u *BookingUpdateOne) SetNillableFromDate(v *time.Time) *BookingUpdateOne {
	if v != nil {
		_u.SetFromDate(*v)
	}
	return _u
}

// SetTillDate sets the "till_date" field.
func (_u *BookingUpdateOne) SetTillDate(v time.Time) *BookingUpdateOne {
	_u.mutation.SetTillDate(v)
	return _u
}

// SetNillableTillDate sets the "till_date" field if the given value is not nil.
func (_u *BookingUpdateOne) SetNillableTillDate(v *time.Time) *BookingUpdateOne {
	if v != nil {
		_u.SetTillDate(*v)
	}
	return _u
}

// SetCanceled sets the "canceled" field.
func (_u *BookingUpdateOne) SetCanceled(v bool) *BookingUpdateOne {
	_u.mutation.SetCanceled(v)
	return _u
}

// SetNillableCanceled sets the "canceled" field if the given value is not nil.
func (_u *BookingUpdateOne) SetNillableCanceled(v *bool) *BookingUpdateOne {
	if v != nil {
		_u.SetCanceled(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BookingUpdateOne) SetUser(v *User) *BookingUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetRoom sets the "room" edge to the Room entity.
func (_u *BookingUpdateOne) SetRoom(v *Room) *BookingUpdateOne {
	return _u.SetRoomID(v.ID)
}

// Mutation returns the BookingMutation object of the builder.
func (_u *BookingUpdateOne) Mutation() *BookingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BookingUpdateOne) ClearUser() *BookingUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearRoom clears the "room" edge to the Room entity.
func (_u *BookingUpdateOne) ClearRoom() *BookingUpdateOne {
	_u.mutation.ClearRoom()
	return _u
}

// Where appends a list predicates to the BookingUpdate builder.
func (_u *BookingUpdateOne) Where(ps ...predicate.Booking) *BookingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookingUpdateOne) Select(field string, fields ...string) *BookingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Booking entity.
func (_u *BookingUpdateOne) Save(ctx context.Context) (*Booking, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookingUpdateOne) SaveX(ctx context.Context) *Booking {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookingUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Booking.user"`)
	}
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Booking.room"`)
	}
	return nil
}

func (_u *BookingUpdateOne) sqlSave(ctx context.Context) (_node *Booking, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(booking.Table, booking.Columns, sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Booking.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, booking.FieldID)
		for _, f := range fields {
			if !booking.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != booking.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NumPersons(); ok {
		_spec.SetField(booking.FieldNumPersons, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumPersons(); ok {
		_spec.AddField(booking.FieldNumPersons, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FromDate(); ok {
		_spec.SetField(booking.FieldFromDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TillDate(); ok {
		_spec.SetField(booking.FieldTillDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Canceled(); ok {
		_spec.SetField(booking.FieldCanceled, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.UserTable,
			Columns: []string{booking.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.UserTable,
			Columns: []string{booking.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.RoomTable,
			Columns: []string{booking.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.RoomTable,
			Columns: []string{booking.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Booking{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{booking.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
