// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fulltimegodev/hotel-reservation/ent/hotel"
	"github.com/fulltimegodev/hotel-reservation/ent/room"
)

// HotelCreate is the builder for creating a Hotel entity.
type HotelCreate struct {
	config
	mutation *HotelMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *HotelCreate) SetName(v string) *HotelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLocation sets the "location" field.
func (_c *HotelCreate) SetLocation(v string) *HotelCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetRating sets the "rating" field.
func (_c *HotelCreate) SetRating(v int) *HotelCreate {
	_c.mutation.SetRating(v)
	return _c
}

// AddRoomIDs adds the "rooms" edge to the Room entity by IDs.
func (_c *HotelCreate) AddRoomIDs(ids ...int) *HotelCreate {
	_c.mutation.AddRoomIDs(ids...)
	return _c
}

// AddRooms adds the "rooms" edges to the Room entity.
func (_c *HotelCreate) AddRooms(v ...*Room) *HotelCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRoomIDs(ids...)
}

// Mutation returns the HotelMutation object of the builder.
func (_c *HotelCreate) Mutation() *HotelMutation {
	return _c.mutation
}

// Save creates the Hotel in the database.
func (_c *HotelCreate) Save(ctx context.Context) (*Hotel, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HotelCreate) SaveX(ctx context.Context) *Hotel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HotelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HotelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HotelCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Hotel.name"`)}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "Hotel.location"`)}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "Hotel.rating"`)}
	}
	return nil
}

func (_c *HotelCreate) sqlSave(ctx context.Context) (*Hotel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HotelCreate) createSpec() (*Hotel, *sqlgraph.CreateSpec) {
	var (
		_node = &Hotel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hotel.Table, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(hotel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(hotel.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(hotel.FieldRating, field.TypeInt, value)
		_node.Rating = value
	}
	if nodes := _c.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.RoomsTable,
			Columns: []string{hotel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HotelCreateBulk is the builder for creating many Hotel entities in bulk.
type HotelCreateBulk struct {
	config
	err      error
	builders []*HotelCreate
}

// Save creates the Hotel entities in the database.
func (_c *HotelCreateBulk) Save(ctx context.Context) ([]*Hotel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Hotel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HotelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HotelCreateBulk) SaveX(ctx context.Context) []*Hotel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HotelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HotelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
