// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fulltimegodev/hotel-reservation/ent/hotel"
	"github.com/fulltimegodev/hotel-reservation/ent/predicate"
	"github.com/fulltimegodev/hotel-reservation/ent/room"
)

// HotelUpdate is the builder for updating Hotel entities.
type HotelUpdate struct {
	config
	hooks    []Hook
	mutation *HotelMutation
}

// Where appends a list predicates to the HotelUpdate builder.
func (_u *HotelUpdate) Where(ps ...predicate.Hotel) *HotelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *HotelUpdate) SetName(v string) *HotelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableName(v *string) *HotelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *HotelUpdate) SetLocation(v string) *HotelUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableLocation(v *string) *HotelUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *HotelUpdate) SetRating(v int) *HotelUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableRating(v *int) *HotelUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *HotelUpdate) AddRating(v int) *HotelUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// AddRoomIDs adds the "rooms" edge to the Room entity by IDs.
func (_u *HotelUpdate) AddRoomIDs(ids ...int) *HotelUpdate {
	_u.mutation.AddRoomIDs(ids...)
	return _u
}

// AddRooms adds the "rooms" edges to the Room entity.
func (_u *HotelUpdate) AddRooms(v ...*Room) *HotelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoomIDs(ids...)
}

// Mutation returns the HotelMutation object of the builder.
func (_u *HotelUpdate) Mutation() *HotelMutation {
	return _u.mutation
}

// ClearRooms clears all "rooms" edges to the Room entity.
func (_u *HotelUpdate) ClearRooms() *HotelUpdate {
	_u.mutation.ClearRooms()
	return _u
}

// RemoveRoomIDs removes the "rooms" edge to Room entities by IDs.
func (_u *HotelUpdate) RemoveRoomIDs(ids ...int) *HotelUpdate {
	_u.mutation.RemoveRoomIDs(ids...)
	return _u
}

// RemoveRooms removes "rooms" edges to Room entities.
func (_u *HotelUpdate) RemoveRooms(v ...*Room) *HotelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoomIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HotelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HotelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *HotelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(hotel.Table, hotel.Columns, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hotel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(hotel.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(hotel.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(hotel.FieldRating, field.TypeInt, value)
	}
	if _u.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.RoomsTable,
			Columns: []string{hotel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoomsIDs(); len(nodes) > 0 && !_u.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.RoomsTable,
			Columns: []string{hotel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.RoomsTable,
			Columns: []string{hotel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HotelUpdateOne is the builder for updating a single Hotel entity.
type HotelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HotelMutation
}

// SetName sets the "name" field.
func (_u *HotelUpdateOne) SetName(v string) *HotelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableName(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *HotelUpdateOne) SetLocation(v string) *HotelUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableLocation(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *HotelUpdateOne) SetRating(v int) *HotelUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableRating(v *int) *HotelUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *HotelUpdateOne) AddRating(v int) *HotelUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// AddRoomIDs adds the "rooms" edge to the Room entity by IDs.
func (_u *HotelUpdateOne) AddRoomIDs(ids ...int) *HotelUpdateOne {
	_u.mutation.AddRoomIDs(ids...)
	return _u
}

// AddRooms adds the "rooms" edges to the Room entity.
func (_u *HotelUpdateOne) AddRooms(v ...*Room) *HotelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoomIDs(ids...)
}

// Mutation returns the HotelMutation object of the builder.
func (_u *HotelUpdateOne) Mutation() *HotelMutation {
	return _u.mutation
}

// ClearRooms clears all "rooms" edges to the Room entity.
func (_u *HotelUpdateOne) ClearRooms() *HotelUpdateOne {
	_u.mutation.ClearRooms()
	return _u
}

// RemoveRoomIDs removes the "rooms" edge to Room entities by IDs.
func (_u *HotelUpdateOne) RemoveRoomIDs(ids ...int) *HotelUpdateOne {
	_u.mutation.RemoveRoomIDs(ids...)
	return _u
}

// RemoveRooms removes "rooms" edges to Room entities.
func (_u *HotelUpdateOne) RemoveRooms(v ...*Room) *HotelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoomIDs(ids...)
}

// Where appends a list predicates to the HotelUpdate builder.
func (_u *HotelUpdateOne) Where(ps ...predicate.Hotel) *HotelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HotelUpdateOne) Select(field string, fields ...string) *HotelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Hotel entity.
func (_u *HotelUpdateOne) Save(ctx context.Context) (*Hotel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotelUpdateOne) SaveX(ctx context.Context) *Hotel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HotelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *HotelUpdateOne) sqlSave(ctx context.Context) (_node *Hotel, err error) {
	_spec := sqlgraph.NewUpdateSpec(hotel.Table, hotel.Columns, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hotel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hotel.FieldID)
		for _, f := range fields {
			if !hotel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hotel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hotel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(hotel.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(hotel.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(hotel.FieldRating, field.TypeInt, value)
	}
	if _u.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.RoomsTable,
			Columns: []string{hotel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoomsIDs(); len(nodes) > 0 && !_u.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.RoomsTable,
			Columns: []string{hotel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.RoomsTable,
			Columns: []string{hotel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Hotel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
