// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fulltimegodev/hotel-reservation/ent/hotel"
	"github.com/fulltimegodev/hotel-reservation/ent/room"
)

// Room is the model entity for the Room schema.
type Room struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Size holds the value of the "size" field.
	Size string `json:"size,omitempty"`
	// Seaside holds the value of the "seaside" field.
	Seaside bool `json:"seaside,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// HotelID holds the value of the "hotel_id" field.
	HotelID int `json:"hotel_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoomQuery when eager-loading is set.
	Edges        RoomEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RoomEdges holds the relations/edges for other nodes in the graph.
type RoomEdges struct {
	// Hotel holds the value of the hotel edge.
	Hotel *Hotel `json:"hotel,omitempty"`
	// Bookings holds the value of the bookings edge.
	Bookings []*Booking `json:"bookings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// HotelOrErr returns the Hotel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoomEdges) HotelOrErr() (*Hotel, error) {
	if e.Hotel != nil {
		return e.Hotel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: hotel.Label}
	}
	return nil, &NotLoadedError{edge: "hotel"}
}

// BookingsOrErr returns the Bookings value or an error if the edge
// was not loaded in eager-loading.
func (e RoomEdges) BookingsOrErr() ([]*Booking, error) {
	if e.loadedTypes[1] {
		return e.Bookings, nil
	}
	return nil, &NotLoadedError{edge: "bookings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Room) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case room.FieldSeaside:
			values[i] = new(sql.NullBool)
		case room.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case room.FieldID, room.FieldHotelID:
			values[i] = new(sql.NullInt64)
		case room.FieldSize:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Room fields.
func (_m *Room) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case room.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case room.FieldSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.String
			}
		case room.FieldSeaside:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field seaside", values[i])
			} else if value.Valid {
				_m.Seaside = value.Bool
			}
		case room.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case room.FieldHotelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hotel_id", values[i])
			} else if value.Valid {
				_m.HotelID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Room.
// This includes values selected through modifiers, order, etc.
func (_m *Room) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHotel queries the "hotel" edge of the Room entity.
func (_m *Room) QueryHotel() *HotelQuery {
	return NewRoomClient(_m.config).QueryHotel(_m)
}

// QueryBookings queries the "bookings" edge of the Room entity.
func (_m *Room) QueryBookings() *BookingQuery {
	return NewRoomClient(_m.config).QueryBookings(_m)
}

// Update returns a builder for updating this Room.
// Note that you need to call Room.Unwrap() before calling this method if this Room
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Room) Update() *RoomUpdateOne {
	return NewRoomClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Room entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Room) Unwrap() *Room {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Room is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Room) String() string {
	var builder strings.Builder
	builder.WriteString("Room(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("size=")
	builder.WriteString(_m.Size)
	builder.WriteString(", ")
	builder.WriteString("seaside=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seaside))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("hotel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HotelID))
	builder.WriteByte(')')
	return builder.String()
}

// Rooms is a parsable slice of Room.
type Rooms []*Room
