// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fulltimegodev/hotel-reservation/ent/booking"
	"github.com/fulltimegodev/hotel-reservation/ent/hotel"
	"github.com/fulltimegodev/hotel-reservation/ent/room"
)

// RoomCreate is the builder for creating a Room entity.
type RoomCreate struct {
	config
	mutation *RoomMutation
	hooks    []Hook
}

// SetSize sets the "size" field.
func (_c *RoomCreate) SetSize(v string) *RoomCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetSeaside sets the "seaside" field.
func (_c *RoomCreate) SetSeaside(v bool) *RoomCreate {
	_c.mutation.SetSeaside(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *RoomCreate) SetPrice(v float64) *RoomCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetHotelID sets the "hotel_id" field.
func (_c *RoomCreate) SetHotelID(v int) *RoomCreate {
	_c.mutation.SetHotelID(v)
	return _c
}

// SetHotel sets the "hotel" edge to the Hotel entity.
func (_c *RoomCreate) SetHotel(v *Hotel) *RoomCreate {
	return _c.SetHotelID(v.ID)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_c *RoomCreate) AddBookingIDs(ids ...int) *RoomCreate {
	_c.mutation.AddBookingIDs(ids...)
	return _c
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_c *RoomCreate) AddBookings(v ...*Booking) *RoomCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBookingIDs(ids...)
}

// Mutation returns the RoomMutation object of the builder.
func (_c *RoomCreate) Mutation() *RoomMutation {
	return _c.mutation
}

// Save creates the Room in the database.
func (_c *RoomCreate) Save(ctx context.Context) (*Room, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoomCreate) SaveX(ctx context.Context) *Room {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoomCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoomCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoomCreate) check() error {
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Room.size"`)}
	}
	if _, ok := _c.mutation.Seaside(); !ok {
		return &ValidationError{Name: "seaside", err: errors.New(`ent: missing required field "Room.seaside"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Room.price"`)}
	}
	if _, ok := _c.mutation.HotelID(); !ok {
		return &ValidationError{Name: "hotel_id", err: errors.New(`ent: missing required field "Room.hotel_id"`)}
	}
	if len(_c.mutation.HotelIDs()) == 0 {
		return &ValidationError{Name: "hotel", err: errors.New(`ent: missing required edge "Room.hotel"`)}
	}
	return nil
}

func (_c *RoomCreate) sqlSave(ctx context.Context) (*Room, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoomCreate) createSpec() (*Room, *sqlgraph.CreateSpec) {
	var (
		_node = &Room{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(room.Table, sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(room.FieldSize, field.TypeString, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Seaside(); ok {
		_spec.SetField(room.FieldSeaside, field.TypeBool, value)
		_node.Seaside = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(room.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if nodes := _c.mutation.HotelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.HotelTable,
			Columns: []string{room.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HotelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RoomCreateBulk is the builder for creating many Room entities in bulk.
type RoomCreateBulk struct {
	config
	err      error
	builders []*RoomCreate
}

// Save creates the Room entities in the database.
func (_c *RoomCreateBulk) Save(ctx context.Context) ([]*Room, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Room, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoomCreateBulk) SaveX(ctx context.Context) []*Room {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoomCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoomCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
