// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fulltimegodev/hotel-reservation/ent/booking"
	"github.com/fulltimegodev/hotel-reservation/ent/hotel"
	"github.com/fulltimegodev/hotel-reservation/ent/predicate"
	"github.com/fulltimegodev/hotel-reservation/ent/room"
)

// RoomUpdate is the builder for updating Room entities.
type RoomUpdate struct {
	config
	hooks    []Hook
	mutation *RoomMutation
}

// Where appends a list predicates to the RoomUpdate builder.
func (_u *RoomUpdate) Where(ps ...predicate.Room) *RoomUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSize sets the "size" field.
func (_u *RoomUpdate) SetSize(v string) *RoomUpdate {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableSize(v *string) *RoomUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// SetSeaside sets the "seaside" field.
func (_u *RoomUpdate) SetSeaside(v bool) *RoomUpdate {
	_u.mutation.SetSeaside(v)
	return _u
}

// SetNillableSeaside sets the "seaside" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableSeaside(v *bool) *RoomUpdate {
	if v != nil {
		_u.SetSeaside(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *RoomUpdate) SetPrice(v float64) *RoomUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *RoomUpdate) SetNillablePrice(v *float64) *RoomUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *RoomUpdate) AddPrice(v float64) *RoomUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetHotelID sets the "hotel_id" field.
func (_u *RoomUpdate) SetHotelID(v int) *RoomUpdate {
	_u.mutation.SetHotelID(v)
	return _u
}

// SetNillableHotelID sets the "hotel_id" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableHotelID(v *int) *RoomUpdate {
	if v != nil {
		_u.SetHotelID(*v)
	}
	return _u
}

// SetHotel sets the "hotel" edge to the Hotel entity.
func (_u *RoomUpdate) SetHotel(v *Hotel) *RoomUpdate {
	return _u.SetHotelID(v.ID)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_u *RoomUpdate) AddBookingIDs(ids ...int) *RoomUpdate {
	_u.mutation.AddBookingIDs(ids...)
	return _u
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_u *RoomUpdate) AddBookings(v ...*Booking) *RoomUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookingIDs(ids...)
}

// Mutation returns the RoomMutation object of the builder.
func (_u *RoomUpdate) Mutation() *RoomMutation {
	return _u.mutation
}

// ClearHotel clears the "hotel" edge to the Hotel entity.
func (_u *RoomUpdate) ClearHotel() *RoomUpdate {
	_u.mutation.ClearHotel()
	return _u
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (_u *RoomUpdate) ClearBookings() *RoomUpdate {
	_u.mutation.ClearBookings()
	return _u
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (_u *RoomUpdate) RemoveBookingIDs(ids ...int) *RoomUpdate {
	_u.mutation.RemoveBookingIDs(ids...)
	return _u
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (_u *RoomUpdate) RemoveBookings(v ...*Booking) *RoomUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoomUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoomUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoomUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoomUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoomUpdate) check() error {
	if _u.mutation.HotelCleared() && len(_u.mutation.HotelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Room.hotel"`)
	}
	return nil
}

func (_u *RoomUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(room.FieldSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seaside(); ok {
		_spec.SetField(room.FieldSeaside, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(room.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(room.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.HotelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.HotelTable,
			Columns: []string{room.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HotelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.HotelTable,
			Columns: []string{room.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !_u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoomUpdateOne is the builder for updating a single Room entity.
type RoomUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoomMutation
}

// SetSize sets the "size" field.
func (_u *RoomUpdateOne) SetSize(v string) *RoomUpdateOne {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableSize(v *string) *RoomUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// SetSeaside sets the "seaside" field.
func (_u *RoomUpdateOne) SetSeaside(v bool) *RoomUpdateOne {
	_u.mutation.SetSeaside(v)
	return _u
}

// SetNillableSeaside sets the "seaside" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableSeaside(v *bool) *RoomUpdateOne {
	if v != nil {
		_u.SetSeaside(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *RoomUpdateOne) SetPrice(v float64) *RoomUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillablePrice(v *float64) *RoomUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *RoomUpdateOne) AddPrice(v float64) *RoomUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetHotelID sets the "hotel_id" field.
func (_u *RoomUpdateOne) SetHotelID(v int) *RoomUpdateOne {
	_u.mutation.SetHotelID(v)
	return _u
}

// SetNillableHotelID sets the "hotel_id" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableHotelID(v *int) *RoomUpdateOne {
	if v != nil {
		_u.SetHotelID(*v)
	}
	return _u
}

// SetHotel sets the "hotel" edge to the Hotel entity.
func (_u *RoomUpdateOne) SetHotel(v *Hotel) *RoomUpdateOne {
	return _u.SetHotelID(v.ID)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_u *RoomUpdateOne) AddBookingIDs(ids ...int) *RoomUpdateOne {
	_u.mutation.AddBookingIDs(ids...)
	return _u
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_u *RoomUpdateOne) AddBookings(v ...*Booking) *RoomUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookingIDs(ids...)
}

// Mutation returns the RoomMutation object of the builder.
func (_u *RoomUpdateOne) Mutation() *RoomMutation {
	return _u.mutation
}

// ClearHotel clears the "hotel" edge to the Hotel entity.
func (_u *RoomUpdateOne) ClearHotel() *RoomUpdateOne {
	_u.mutation.ClearHotel()
	return _u
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (_u *RoomUpdateOne) ClearBookings() *RoomUpdateOne {
	_u.mutation.ClearBookings()
	return _u
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (_u *RoomUpdateOne) RemoveBookingIDs(ids ...int) *RoomUpdateOne {
	_u.mutation.RemoveBookingIDs(ids...)
	return _u
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (_u *RoomUpdateOne) RemoveBookings(v ...*Booking) *RoomUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookingIDs(ids...)
}

// Where appends a list predicates to the RoomUpdate builder.
func (_u *RoomUpdateOne) Where(ps ...predicate.Room) *RoomUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoomUpdateOne) Select(field string, fields ...string) *RoomUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Room entity.
func (_u *RoomUpdateOne) Save(ctx context.Context) (*Room, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoomUpdateOne) SaveX(ctx context.Context) *Room {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoomUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoomUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoomUpdateOne) check() error {
	if _u.mutation.HotelCleared() && len(_u.mutation.HotelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Room.hotel"`)
	}
	return nil
}

func (_u *RoomUpdateOne) sqlSave(ctx context.Context) (_node *Room, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Room.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, room.FieldID)
		for _, f := range fields {
			if !room.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != room.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(room.FieldSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seaside(); ok {
		_spec.SetField(room.FieldSeaside, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(room.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(room.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.HotelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.HotelTable,
			Columns: []string{room.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HotelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.HotelTable,
			Columns: []string{room.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !_u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Room{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
