// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/fulltimegodev/hotel-reservation/ent/booking"
	"github.com/fulltimegodev/hotel-reservation/ent/schema"
	"github.com/fulltimegodev/hotel-reservation/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookingFields := schema.Booking{}.Fields()
	_ = bookingFields
	// bookingDescCanceled is the schema descriptor for canceled field.
	bookingDescCanceled := bookingFields[5].Descriptor()
	// booking.DefaultCanceled holds the default value on creation for the canceled field.
	booking.DefaultCanceled = bookingDescCanceled.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[4].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
}
