// Code generated by ent, DO NOT EDIT.

package room

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldSeaside holds the string denoting the seaside field in the database.
	FieldSeaside = "seaside"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldHotelID holds the string denoting the hotel_id field in the database.
	FieldHotelID = "hotel_id"
	// EdgeHotel holds the string denoting the hotel edge name in mutations.
	EdgeHotel = "hotel"
	// EdgeBookings holds the string denoting the bookings edge name in mutations.
	EdgeBookings = "bookings"
	// Table holds the table name of the room in the database.
	Table = "rooms"
	// HotelTable is the table that holds the hotel relation/edge.
	HotelTable = "rooms"
	// HotelInverseTable is the table name for the Hotel entity.
	// It exists in this package in order to avoid circular dependency with the "hotel" package.
	HotelInverseTable = "hotels"
	// HotelColumn is the table column denoting the hotel relation/edge.
	HotelColumn = "hotel_id"
	// BookingsTable is the table that holds the bookings relation/edge.
	BookingsTable = "bookings"
	// BookingsInverseTable is the table name for the Booking entity.
	// It exists in this package in order to avoid circular dependency with the "booking" package.
	BookingsInverseTable = "bookings"
	// BookingsColumn is the table column denoting the bookings relation/edge.
	BookingsColumn = "room_id"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldSize,
	FieldSeaside,
	FieldPrice,
	FieldHotelID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Room queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// BySeaside orders the results by the seaside field.
func BySeaside(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeaside, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByHotelID orders the results by the hotel_id field.
func ByHotelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHotelID, opts...).ToFunc()
}

// ByHotelField orders the results by hotel field.
func ByHotelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHotelStep(), sql.OrderByField(field, opts...))
	}
}

// ByBookingsCount orders the results by bookings count.
func ByBookingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBookingsStep(), opts...)
	}
}

// ByBookings orders the results by bookings terms.
func ByBookings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBookingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newHotelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HotelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HotelTable, HotelColumn),
	)
}
func newBookingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BookingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BookingsTable, BookingsColumn),
	)
}
